[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor -L defmt"
# runner = 'probe-rs run --chip esp32c3'

rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Trom_functions.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "force-frame-pointers",  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  "--cfg", 'feature="esp32c3"',
]

[unstable]
build-std = ["core", "alloc"]
